### ISSUE TITLE
400 bad request on julialang announcements feed

### ISSUE THREAD

**Issue by garrison** [zenhack/ttrss-sandstorm#14] opened 2020-08-15 00:16 UTC
Hi Ian,

Thank you for updating this!

After upgrading, all my feeds work except for one:  I get a 400 bad request when fetching https://discourse.julialang.org/c/announce/25.rss.  I was also able to reproduce this in a brand new grain.  I can load it in my web browser just fine.  I would assume this applies to other Discourse feeds, but I have not tried others.

**Comment by zenhack** [comment] 2020-08-15 00:46
Thanks for the report, I can reproduce it as well, and confirm that it's a discourse issue -- it does the same thing on the ttrss community site and discourse.elm-lang.org. I'll dig in and try to pin down what's going on soonish.

**Comment by zenhack** [comment] 2020-08-15 01:49
Looks like this is a Sandstorm bug; I sent a fix: https://github.com/sandstorm-io/sandstorm/pull/3408

**Comment by zenhack** [comment] 2020-08-16 02:09
I'm going to close this one since there's nothing to do re: ttrss here; we just have to wait until the pr I sent lands.

**Closed as completed by zenhack** 2020-08-16 02:09 UTC
Labels: bug
